### ISSUE TITLE
V-feedback can't be added dynamically

### ISSUE THREAD

**Issue by liujian10** [kilohaty/v-feedback#1]
V-feedback can't be added dynamically because of the grammar of vue;
I think it will be better, as follows
```
Vue.directive('feedback', {
  bind: function (el, binding, vnode) {
    if(binding.value!==undefined && binding.value==="") return;
    VFb.register(vnode.elm, binding.value || 'e-feedback');
  },

  unbind: function (el, binding, vnode) {
    VFb.destroy(vnode.elm);
  }
});
```
When set to "", v-feedback will not be bound;

**Comment by axi1000** [comment]
look this case
[http://jsbin.com/jejuqik/1/edit?html,output](http://jsbin.com/jejuqik/1/edit?html,output)

what version are you using?

**Comment by liujian10** [comment]
哈哈 还是说中文吧，我的意思是建议改成当设置 “” 空字符串的时候 v-feedback 不会生效，这样在动态赋值的时候，设置 "" 值的时候就不会触发v-feedback的逻辑了。

**Comment by axi1000** [comment]
haha
明白了，能告诉一下这个需求的场景吗？因为我还没遇到这样的场景。

**Comment by liujian10** [comment]
比如我想写一个组件，在有点击事件的时候有点击效果，没有点击事件的时候不绑定点击效果，但是 vue 不支持这种根级属性的动态添加，不过有个方案，**可以动态修改渲染后的 dom 元素属性**，哈哈，我就这么干吧，谢咯

**Comment by axi1000** [comment]
已经支持了动态数据，请看一下demo是不是你想要的。
或者项目文件 src/example.html 也有相同的案例。
[http://jsbin.com/wucazeq/edit?html,output](http://jsbin.com/wucazeq/edit?html,output)

**Comment by liujian10** [comment]
哈哈 点个赞
